[tasks.clean-coverage]
description = "Clean the project and remove extra coverage files"
script = [
    "cargo clean",
    "rm -f profile-*",
    "rm -rf coverage"
]

[tasks.run-tests]
description = "Run tests with coverage instrumentation"
command = "cargo"
args = ["test"]
[tasks.run-tests.env]
CARGO_TARGET_DIR = "target"
RUSTFLAGS = "-C instrument-coverage"
LLVM_PROFILE_FILE = "profile-%p-%m.profraw"

[tasks.generate-coverage]
description = "Generate HTML coverage report using grcov"
command = "grcov"
args = [
    ".",
    "--binary-path", "target/debug/deps",
    "--source-dir", ".",
    "--output-type", "html",
    "--output-path", "coverage",
    "--branch",
    "--ignore-not-existing"
]

[tasks.coverage-grcov]
description = "Run full coverage process (clean, test, and generate grcov report)"
dependencies = ["clean-coverage", "run-tests", "generate-coverage"]
